# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQmwt2whVhOllVjqU28TTllryyv8O35S
"""

import streamlit as st
import requests
from PIL import Image
from io import BytesIO
import pandas as pd
import plotly.express as px

# 스트림릿 페이지 설정
st.set_page_config(
    page_title="공공데이터 애널리틱스 - 6조 기말 발표",
    page_icon="🌿",
    layout="wide"
)

# 스트림릿 커스텀 스타일링
st.markdown(
    """
    <style>
    .reportview-container {
        background: #f0fff4;
    }
    .sidebar .sidebar-content {
        background: #e6ffed;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# 사이드바 설정
with st.sidebar:
    st.markdown("## 공공데이터 애널리틱스 \n 6조 기말 발표")
    st.markdown("---")
    st.markdown("### 목차")
    st.markdown("### 선행연구")
    st.markdown("### 분석 결과")
    st.markdown("### Environment (환경)")
    env_options = [
        "온실가스 배출량", "에너지 사용량", "에너지 사용량 대비 온실가스 배출량",
        "용수 사용량", "재사용 용수 비율", "폐기물 배출량",
        "폐기물 재활용 비율", "대기오염 배출량", "수질오염 배출량"
    ]
    env_dropdown = st.selectbox("Environment 옵션 선택", env_options)
    st.markdown("### Social (사회)")
    soc_options = [
        "자발적 이직률", "신규 채용 및 고용 유지", "장애인 고용률",
        "정규직 비율"
    ]
    soc_dropdown = st.selectbox("Social 옵션 선택", soc_options)
    st.markdown("### 중소기업 데이터")
    sme_options = ["중소기업 개수", "중소기업 종사자", "중소기업 매출액"]
    sme_dropdown = st.selectbox("중소기업 데이터 옵션 선택", sme_options)
    st.markdown("### 정책적 시사점")
    st.markdown("### 분석 노트 📝")

# 'Social (사회)' 드롭다운에서 '자발적 이직률' 선택 시 표시할 내용
if soc_dropdown == "자발적 이직률":
    st.markdown("## 자발적 이직률")
    st.markdown("• 조직의 인적자원 관리 수준이 산업평균 대비 적정한 수준을 유지하며 관리되고 있는지 확인")
    st.markdown("• 구성원이 자발적으로 조직을 이동하는 자발적 이직률을 점검(산업적 특성 반영)")

    # 데이터 불러오기
    data_url = 'https://raw.githubusercontent.com/ssunyoungcho/nyong/main/연도별%20산업별%20이동자이동률.csv'
    df = pd.read_csv(data_url, encoding="utf-8")

    

    # Plotly 시각화
    df['year'] = df['year'].astype(int)
    df_move = df.groupby(['year', '산업명'])['이동자'].mean().reset_index()
    df_move_sorted = df_move.sort_values(by=['year', '산업명'])

    fig = px.line(df_move_sorted, x='year', y='이동자', color='산업명', markers=True,
                  title='연도별 산업별 이동자 수 추세 (5개년)',
                  labels={'year': '연도', '이동자': '이동자 수'},
                  color_discrete_sequence=px.colors.qualitative.Dark24)
    fig.update_traces(marker=dict(size=10), line=dict(width=3))
    fig.update_layout(legend_title='산업분류', height=700, plot_bgcolor='#F2F2F2')
    fig.update_xaxes(type='linear')
    fig.update_xaxes(tickvals=[2017, 2018, 2019, 2020, 2021], ticktext=['2017', '2018', '2019', '2020', '2021'])
    fig.update_layout(yaxis=dict(tickformat=',d'))

    st.plotly_chart(fig, use_container_width=True)

  
# 메인 페이지 설정
st.markdown("# 공공데이터 애널리틱스 - 6조 기말 발표")
